# Chapter 3: Conditionals & Exceptions (Coding Exercises)

**Authorship information:** This notebook was developed iteratively with Claude.ai, a large language model, for Phy 225 taught by Prof. Bryanne McDonough. The LLM was provided the chapter contents and asked to propose appropriate exercises based on concepts from Modern Physics. Prof. McDonough then selected the most pedagogically relevant exercises and prompted the LLM to create a Jupyter notebook with appropriate notes and the selected exercises. The generated content was read thoroughly for accuracy and changes were made. For instance, before corrections, the EM spectrum regions incorrectly left open the bounds for UV and IR radiation. 

Both humans and LLMs can (and will) make mistakes. If you find a problem with the content in this notebook, whether it is an error or feedback, you can report the issue by emailing your instructor or raising a [Github issue in the repository](https://github.com/Prof-McDonough/intro-to-python/issues).

---

The exercises below assume that you have read [Chapter 3 <img height="12" style="display: inline-block" src="../static/link/to_nb.png">](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/main/03_conditionals/00_content.ipynb).

The `...`'s in the code cells indicate where you need to fill in code snippets. The number of `...`'s within a code cell give you a rough idea of how many lines of code are needed to solve the task. You should not need to create any additional code cells for your final solution. However, you may want to use temporary code cells to try out some ideas.

## The Heisenberg Uncertainty Principle

In classical physics, we assume that we can measure properties of objects with arbitrary precision, limited only by the quality of our instruments. However, quantum mechanics reveals a fundamental limit to how precisely we can know certain pairs of properties simultaneously.

The **Heisenberg Uncertainty Principle** states that there is a fundamental limit to the precision with which certain pairs of physical properties (called conjugate variables) can be known simultaneously. The most famous form involves position ($x$) and momentum ($p$):

$$\Delta x \Delta p \geq \frac{\hbar}{2}$$

where:
- $\Delta x$ is the uncertainty in position (measured in meters)
- $\Delta p$ is the uncertainty in momentum (measured in kg·m/s)
- $\hbar = \frac{h}{2\pi} = 1.054571817 \times 10^{-34}$ J·s is the reduced Planck constant

This principle tells us that the more precisely we know a particle's position, the less precisely we can know its momentum, and vice versa. This is not a limitation of our measurement technology—it is a fundamental property of nature at the quantum scale.

**Important:** This inequality must always be satisfied for any quantum mechanical system. If someone proposes a measurement where $\Delta x \Delta p < \frac{\hbar}{2}$, that measurement is physically impossible.

**Q1**: Write a function `check_uncertainty_principle()` that takes two arguments:
- `delta_x`: uncertainty in position (in meters)
- `delta_p`: uncertainty in momentum (in kg·m/s)

The function should return `True` if the proposed measurement satisfies the uncertainty principle, and `False` if it violates the principle (i.e., is physically impossible).

Use $\hbar = 1.054571817 \times 10^{-34}$ J·s.

In [ ]:
def check_uncertainty_principle(delta_x, delta_p):
    """
    Checks if a measurement of position and momentum satisfies 
    the Heisenberg Uncertainty Principle.
    """
    # Reduced Planck constant
    hbar = 1.054571817e-34
    
    # Calculate the minimum allowed product (hbar / 2)
    limit = hbar / 2
    
    # Check the inequality: delta_x * delta_p >= hbar / 2
    if (delta_x * delta_p) >= limit:
        return True
    else:
        return False

# A measurement with very high precision (violates the principle)
print(check_uncertainty_principle(1e-18, 1e-18))  # Returns False

# A measurement with standard precision (satisfies the principle)
print(check_uncertainty_principle(1e-10, 1e-20))  # Returns True

False
True


**Q2**: Test your function with the following proposed measurements. For each case, determine if the measurement is physically possible:

a) An electron (mass = $9.109 \times 10^{-31}$ kg) with $\Delta x = 1 \times 10^{-10}$ m (about the size of an atom) and $\Delta p = 1 \times 10^{-24}$ kg·m/s

b) The same electron with $\Delta x = 1 \times 10^{-10}$ m but $\Delta p = 1 \times 10^{-26}$ kg·m/s (much more precise momentum)

c) A proton with $\Delta x = 1 \times 10^{-15}$ m (nuclear scale) and $\Delta p = 1 \times 10^{-20}$ kg·m/s

In [2]:
# Case a
check_uncertainty_principle(1e-10, 1e-24)  # Returns True

True

In [ ]:
# Case b
check_uncertainty_principle(1e-10, 1e-26)  # Returns False

False

In [ ]:
# Case c
check_uncertainty_principle(1e-15, 1e-20)  # Returns False

False

**Q3**: Based on your results from Q2, which measurement(s) are physically impossible? Why might case (b) be impossible while case (a) is possible?

Case b and c are physically impossible. Case b is impossible because Delta_x times delta_p is less than the limit hbar/2. Case a is greater than the limit.

## The Photoelectric Effect (Extended)

You previously learned about the photoelectric effect and how Einstein's explanation earned him the Nobel Prize. Let's review and extend those concepts.

### Review: The Photoelectric Effect

When light strikes a metal surface, it can eject electrons. This phenomenon contradicted classical wave theory in several ways:
- Below a certain threshold frequency, *no* electrons are ejected regardless of light intensity
- Above this threshold, electrons are ejected immediately with no time delay
- The kinetic energy of ejected electrons depends on light frequency, not intensity

Einstein explained this by proposing that light consists of discrete packets of energy called **photons**, where each photon has energy:

$$E = hf = \frac{hc}{\lambda}$$

where:
- $h = 6.62607015 \times 10^{-34}$ J·s is Planck's constant
- $f$ is the frequency of light
- $\lambda$ is the wavelength of light
- $c = 2.998 \times 10^{8}$ m/s is the speed of light

A convenient constant for calculations: $hc = 1240$ eV·nm (when wavelength is in nanometers)

### New Concepts: Work Function and Kinetic Energy

**Work Function ($W$ or $\phi$):** The minimum energy required to remove an electron from a material's surface. This is a property of the material and is measured in electron-volts (eV).

Common work functions:
- Sodium: 2.75 eV
- Aluminum: 4.28 eV
- Copper: 4.65 eV
- Gold: 5.1 eV

**Threshold Wavelength ($\lambda_{\text{threshold}}$):** The maximum wavelength (or minimum frequency) that can eject electrons from a material:

$$\lambda_{\text{threshold}} = \frac{hc}{W}$$

Any photon with $\lambda > \lambda_{\text{threshold}}$ (lower energy) will NOT eject electrons, regardless of intensity!

**Einstein's Photoelectric Equation:** When a photon ejects an electron, the excess energy becomes the electron's kinetic energy:

$$KE_{\text{max}} = E_{\text{photon}} - W = \frac{hc}{\lambda} - W$$

This equation only applies when $E_{\text{photon}} > W$ (or equivalently, $\lambda < \lambda_{\text{threshold}}$). Otherwise, no electrons are ejected and $KE = 0$.

### Electromagnetic Spectrum Regions

Different wavelengths of light fall into different regions:
- **Ultraviolet (UV):** $10$ nm $< \lambda < 380$ nm (higher energy, can damage DNA)
- **Visible:** $380$ nm $\leq \lambda \leq 700$ nm (the light we can see)
- **Infrared (IR):** $700$ nm $< \lambda < 1,000,000$ nm (1 mm) (lower energy, associated with heat)

Wavelengths outside these ranges (λ ≤ 10 nm or λ ≥ 1,000,000 nm) fall into other categories like X-rays, gamma rays, or microwaves, which are beyond the scope of typical photoelectric experiments with metals.

**Q4**: Write a function `can_eject_electron()` that takes two arguments:
- `wavelength`: the wavelength of incident light (in nm)
- `work_function`: the work function of the material (in eV)

The function should return `True` if a photon with the given wavelength has sufficient energy to eject an electron from the material, and `False` otherwise.

Use the convenient constant $hc = 1240$ eV·nm for your calculation.

In [8]:
def can_eject_electron(wavelength, work_function):
    """
    Determines if light of a specific wavelength can eject an electron
    from a metal with a given work function.
    
    Args:
        wavelength (float): Wavelength of light in nm.
        work_function (float): Work function of the metal in eV.
        
    Returns:
        bool: True if ejection is possible, False otherwise.
    """
    # Constant hc in eV*nm
    hc = 1240
    
    # Calculate photon energy: E = hc / lambda
    photon_energy = hc / wavelength
    
    # Check if photon energy meets or exceeds the work function
    if photon_energy >= work_function:
        return True
    else:
        return False
    # Calling the function and printing the result
result_a = can_eject_electron(700, 2.75)  # Red light on Sodium
print(f"Can 700nm light eject an electron from Sodium? {result_a}")

result_b = can_eject_electron(400, 4.28)  # Violet light on Aluminum
print(f"Can 400nm light eject an electron from Aluminum? {result_b}")

Can 700nm light eject an electron from Sodium? False
Can 400nm light eject an electron from Aluminum? False


**Q5**: Write a function `electron_kinetic_energy()` that takes the same two arguments as above and returns the kinetic energy of the ejected electron (in eV).

Important: If the photon energy is insufficient to eject an electron, the function should return `0.0` (since no electron is ejected).

In [9]:
def electron_kinetic_energy(wavelength, work_function):
    """
    Calculates the maximum kinetic energy of an ejected electron.
    Returns 0.0 if the photon energy is less than the work function.
    """
    # Constant hc in eV*nm
    hc = 1240
    
    # Calculate incoming photon energy
    photon_energy = hc / wavelength
    
    # Check if ejection is possible
    if photon_energy > work_function:
        # The leftover energy is kinetic energy
        return photon_energy - work_function
    else:
        # No ejection occurred
        return 0.0

# --- Testing the function ---
# Aluminum (WF = 4.28) hit by deep UV light (200nm)
ke = electron_kinetic_energy(200, 4.28)
print(f"Kinetic Energy of electron from Aluminum at 200nm: {ke:.2f} eV")

# Aluminum hit by visible red light (700nm)
ke_red = electron_kinetic_energy(700, 4.28)
print(f"Kinetic Energy of electron from Aluminum at 700nm: {ke_red:.2f} eV")

Kinetic Energy of electron from Aluminum at 200nm: 1.92 eV
Kinetic Energy of electron from Aluminum at 700nm: 0.00 eV


**Q6**: You have a light source with wavelength 400 nm (violet light). Test whether it can eject electrons from the following materials, and if so, calculate the kinetic energy of the ejected electrons:

- Sodium (W = 2.75 eV)
- Aluminum (W = 4.28 eV)
- Copper (W = 4.65 eV)
- Gold (W = 5.1 eV)

For each material, use both functions you created and print:
1. Whether ejection occurs (True/False)
2. The kinetic energy if ejection occurs

Hint: You may want to store the wavelength and work functions in variables first to make your code more readable.

In [10]:
# Sodium
wavelength = 400
wf_sodium = 2.75

ejection = can_eject_electron(wavelength, wf_sodium)
ke = electron_kinetic_energy(wavelength, wf_sodium)

print(f"Sodium (W = {wf_sodium} eV):")
print(f"Ejection: {ejection}")
print(f"Kinetic Energy: {ke:.2f} eV")

Sodium (W = 2.75 eV):
Ejection: True
Kinetic Energy: 0.35 eV


In [11]:
# Aluminum
wavelength = 400
wf_aluminum = 4.28

ejection = can_eject_electron(wavelength, wf_aluminum)
ke = electron_kinetic_energy(wavelength, wf_aluminum)

print(f"Aluminum (W = {wf_aluminum} eV):")
print(f"Ejection: {ejection}")
print(f"Kinetic Energy: {ke:.2f} eV")

Aluminum (W = 4.28 eV):
Ejection: False
Kinetic Energy: 0.00 eV


In [12]:
# Setup for Copper
wavelength = 400
wf_copper = 4.65

ejection = can_eject_electron(wavelength, wf_copper)
ke = electron_kinetic_energy(wavelength, wf_copper)

print(f"Copper (W = {wf_copper} eV):")
print(f"Ejection: {ejection}")
print(f"Kinetic Energy: {ke:.2f} eV")

Copper (W = 4.65 eV):
Ejection: False
Kinetic Energy: 0.00 eV


In [13]:
# Setup for Gold
wavelength = 400
wf_gold = 5.1

ejection = can_eject_electron(wavelength, wf_gold)
ke = electron_kinetic_energy(wavelength, wf_gold)

print(f"Gold (W = {wf_gold} eV):")
print(f"Ejection: {ejection}")
print(f"Kinetic Energy: {ke:.2f} eV")

Gold (W = 5.1 eV):
Ejection: False
Kinetic Energy: 0.00 eV


**Q7**: Based on your results from Q6, which material(s) did NOT eject electrons? Calculate the threshold wavelength for gold to verify that 400 nm is indeed below the threshold.

In [21]:
# Aluminum, Copper, and Gold did not eject electrons.
# Calculate threshold wavelength for gold
hc = 1240
wf_gold = 5.1

# Calculate threshold wavelength
lambda_threshold_gold = hc / wf_gold

print(f"The threshold wavelength for Gold is: {lambda_threshold_gold:.2f} nm")

The threshold wavelength for Gold is: 243.14 nm


Aluminum, Copper, and Gold did not eject electrons.

**Q8**: Write a function `analyze_photon()` that provides a comprehensive analysis of a photon's interaction with a material. The function should take:
- `wavelength`: wavelength in nm
- `work_function`: work function in eV

The function should:
1. Classify the photon's spectral region (UV, Visible, IR, or Out of Range)
2. Determine if electron ejection occurs
3. Calculate the kinetic energy if ejection occurs
4. Return a string message summarizing all pieces of information

Example outputs:
- `"UV photon (350 nm). Electron ejected with KE = 0.79 eV"`
- `"Visible photon (500 nm). Electron ejected with KE = 0.23 eV"`
- `"IR photon (800 nm). No electron ejection (insufficient energy)"`
- `"Wavelength out of range (5 nm). Cannot classify as UV/Visible/IR"`

Spectral regions:
- UV: 10 nm < λ < 380 nm
- Visible: 380 nm ≤ λ ≤ 700 nm
- IR: 700 nm < λ < 1,000,000 nm
- Out of Range: λ ≤ 10 nm or λ ≥ 1,000,000 nm

Note: For out-of-range wavelengths, your function should identify them as such and not attempt to classify them as UV/Visible/IR or calculate photoelectric effect properties.

Hint: You can use [f-strings](https://www.w3schools.com/python/python_string_formatting.asp) or the `.format()` method to create formatted output. You may also want to use the `round()` function to format the kinetic energy.

In [23]:
def analyze_photon(wavelength, work_function):
    # 1. Classify the spectral region
    if wavelength <= 10 or wavelength >= 1000000:
        return f"Wavelength out of range ({wavelength} nm). Cannot classify as UV /Visible/IR"
    
    if 10 < wavelength < 380:
        region = "UV"
    elif 380 <= wavelength <= 700:
        region = "Visible"
    else: # 700 < wavelength < 1,000,000
        region = "IR"
        
    # 2. Calculate Energy and Ejection
    hc = 1240
    photon_energy = hc / wavelength
    
    if photon_energy >= work_function:
        ke = photon_energy - work_function
        return f"{region} photon ({wavelength} nm). Electron ejected with KE = {round(ke, 2)} eV"
    else:
        return f"{region} photon ({wavelength} nm). No electron ejection (insufficient energy)"

# --- Test Cases ---
print(analyze_photon(350, 2.75))     # UV Example
print(analyze_photon(500, 2.25))     # Visible Example
print(analyze_photon(800, 2.75))     # IR Example
print(analyze_photon(5, 4.0))        # Out of Range Example

UV photon (350 nm). Electron ejected with KE = 0.79 eV
Visible photon (500 nm). Electron ejected with KE = 0.23 eV
IR photon (800 nm). No electron ejection (insufficient energy)
Wavelength out of range (5 nm). Cannot classify as UV /Visible/IR


**Q9**: Test your `analyze_photon()` function with the following scenarios:

a) A 350 nm photon incident on sodium (W = 2.75 eV)

b) A 550 nm photon incident on aluminum (W = 4.28 eV)

c) An 800 nm photon incident on copper (W = 4.65 eV)

d) A 5 nm photon incident on gold (W = 5.1 eV) - this is in the X-ray region!

In [24]:
# Case a
print(analyze_photon(350, 2.75))

UV photon (350 nm). Electron ejected with KE = 0.79 eV


In [ ]:
# Case b
print(analyze_photon(550, 4.28))

IR photon (800 nm). No electron ejection (insufficient energy)


In [26]:
# Case c
print(analyze_photon(800, 4.65))

IR photon (800 nm). No electron ejection (insufficient energy)


In [ ]:
# Case d
print(analyze_photon(5, 5.1))

Wavelength out of range (5 nm). Cannot classify as UV /Visible/IR


: 